data:
  dataset: "kitti"
  root_dir: "/root/autodl-tmp/kitti_dataset"
  crop_height: 256
  crop_width: 512
model:
  max_disp: 192
training:
  num_epochs: 100
  batch_size: 4
  learning_rate: 0.0001
  loss:
    smoothness:
      weight: 0.1      # 开启平滑
    edge_alpha: 15.0   # 开启 15.0 的重度边缘切割
    ohem_fraction: 1.0 # 依然关闭困难挖掘
    relative_loss_weight: 0.0 # 依然关闭 EDW
logging:
  checkpoint_dir: "./checkpoints_ablation_2"
  tensorboard_dir: "./tensorboard_ablation_2"